#
#      Authors: Kordowski Mateusz, Przybysz Filip
#

Import('env_base')
Import('binFolder')
Import('pathToUtility')
Import('pathToControls')
Import('libraryPath')

pathToH = '#include/main/event/'
libraryName = 'events'

HFilesMain = [
    'Interface.h',
    'ToggleInterface.h',
    'Basic.cc',
    'Control.cc',
    'Set.cc',
    'Manager.cc',
    'UI.cc'
]

HFilesUtility = [
    'SetTemplate.hpp'
]

HFilesControls = [
    'ControlMapping.h'
]

filesCPP = [
    'Basic.cc',
    'Control.cc',
    'Set.cc',
    'Manager.cc',
    'UI.cc'
]



filesHMain = [pathToH + x for x in HFilesMain]
filesHUtil = [pathToUtility + x for x in HFilesUtility]
filesHControl = [pathToControls + x for x in HFilesControls]

env = env_base.Clone()

env.Append(CPPPATH = pathToH)

env.StaticLibrary(libraryPath + libraryName, filesCPP)
