

Import('env_base')
Import('binFolder')
Import('pathToUtility')
Import('libraryPath')

pathToH = '#include/main/drawing/'
libraryName = 'drawing'

HFilesMain = [
    'drawable.h',
    'drawingID.h',
    'drawSetFactory.h',
]

HFilesUtility = [
    'ID.h',
    'setTemplate.h'
]

filesCPP = [
    'drawManager.cpp',
    'drawManagerBridgeToSets.cpp'
]


filesHMain = [pathToH + x for x in HFilesMain]
filesHUtil = [pathToUtility + x for x in HFilesUtility]

env = env_base.Clone()

env.Append(CPPPATH = pathToH)

env.StaticLibrary(libraryPath + libraryName, filesCPP)