#
#      Author: Przybysz Filip
#
Import('env_tests')
Import('binFolder')
Import('sys')

pathToH = '#include/main/collision'

env = env_tests.Clone()

env.Append(
    CPPPATH = [
        '#libraries/boost_1_72_0',
	pathToH
    ]
)

if sys.platform.startswith('linux'):
    objectFiles = [
	'../../bin/BoostTestInclude.o'
    ]
else:
    objectFiles = [
	'../../bin/BoostTestInclude.obj'
    ]

CPPFiles = [
    'CollisionTests.cc'
]

env.Program(target = "CollisionTests", source = CPPFiles + objectFiles)

