#
#      Author: Przybysz Filip
#

Import('env_base')
Import('libraryPath')
Import('binFolder')
Import('sys')

env_tests = env_base.Clone();

testLibraries = [
    'screenLib',
    'events', 
    'drawing',
    'collision',
    'sfml-graphics',
    'sfml-window',
    'sfml-system',
    'Box2D'
]

env_tests.Append(
LIBS = [
        testLibraries
    ],

LIBPATH = [
        libraryPath
    ]
)

#object for faster compilation
env_tests.Object(target = 'BoostTestInclude', source = 'BoostTestInclude.cc')

#compile tests
SConscript(
    'main/screen/SConscript', 
    exports = ['env_tests', 'binFolder', 'sys'], 
    duplicate=0
    )

SConscript(
    'main/program_events/SConscript', 
    exports = ['env_tests', 'binFolder', 'sys'], 
    duplicate=0
    )

SConscript(
    'main/collision/SConscript', 
    exports = ['env_tests', 'binFolder', 'sys'], 
    duplicate=0
    )

