
Import('env_base')
Import('binFolder')
Import('pathToUtility')
Import('libraryPath')

pathToH = '#include/main/collision/'
libraryName = 'collision'

HFilesMain = [
    'collisionID.h',
    'collisionInterface.h',
    'collisionManager.h',
    'collisionManagerBridgeToSets.h'
]

HFilesUtility = [
    'ID.h'
]

filesCPP = [
    'sensor.cpp'
]

filesHMain = [pathToH + x for x in HFilesMain]
filesHUtil = [pathToUtility + x for x in HFilesUtility]

env = env_base.Clone()

env.Append(CPPPATH = pathToH)

env.StaticLibrary(libraryPath + libraryName, filesCPP)