#
#      Authors: Kordowski Mateusz, Przybysz Filip
#

Import('env_base')
Import('binFolder')
Import('pathToUtility')
Import('libraryPath')

pathToH = '#include/main/collision/'
libraryName = 'collision'

HFilesMain = [
    'CollisionID.h',
    'CollisionInterface.h',
    'CollisionManager.h',
    'CollisionManagerBridgeToSets.h'
]

HFilesUtility = [
    'ID.hpp'
]

filesCPP = [
    'Sensor.cc'
]

filesHMain = [pathToH + x for x in HFilesMain]
filesHUtil = [pathToUtility + x for x in HFilesUtility]

env = env_base.Clone()

env.Append(
    CPPPATH = [
        pathToH
        ],
)

env.StaticLibrary(libraryPath + libraryName, filesCPP)
