#
#      Authors: Przybysz Filip
#

Import('env_base')
Import('binFolder')
Import('pathToUtility')
Import('libraryPath')

pathToH = '#include/main/graph/'
libraryName = 'graph'

HeaderFiles = [
    'Graph.h',
    'GraphUtility.hpp'
]

env = env_base.Clone()

filesCPP = [
    Glob('*.cc')
]


filesH = [pathToH + x for x in HeaderFiles]

env.Append(
    CPPPATH = [
        pathToH
    ]
    )

env.StaticLibrary(
    target = libraryPath + libraryName, 
    source = filesCPP)
