
Import('env_base')

env = env_base.Clone(
    CPPPATH = ['../../../source/main/screen', '../../../source/main/utility']
)

env.StaticLibrary('../../../build/libs/screenLib', ['screenID.cpp', 'screenID.h', 'screenInterface.h',  'screenManager.cpp', 'startScreen.cpp', '../../../source/main/utility/ID.h'])
