
Import('env_base')

env = env_base.Clone(
    CPPPATH = [
        '../../../source/main/screen', 
        '../../../source/main/utility'
    ]
)

filesH = [
    'screenInterface.h',
    'screenID.h',
    '../../../source/main/utility/ID.h'
]

filesCPP = [
    'screenID.cpp',
    'screenManager.cpp',
    'startScreen.cpp'
]

libraryName = 'screenLib'
libraryPath = '../../../build/libs/'

env.StaticLibrary(libraryPath + libraryName, filesH + filesCPP)
