#
#      Authors: Kordowski Mateusz, Przybysz Filip
#

Import('env_base')
Import('binFolder')
Import('pathToUtility')
Import('libraryPath')

pathToH = '#include/main/screen/'
pathToH2 = '#include/main/event/'
libraryName = 'screenLib'

HFilesMain = [
    'ScreenInterface.h',
    'ScreenID.h',
]

HFilesUtility = [
    'ID.hpp'
]

env = env_base.Clone()

filesCPP = [
    Glob('*.cc'),
    Glob('../event/*.cc') #TODO:causes SCons environment warnings, maybe compile object separately
]


filesHMain = [pathToH + x for x in HFilesMain]
filesHUtil = [pathToUtility + x for x in HFilesUtility]

env.Append(
    CPPPATH = [
        pathToH, 
        pathToH2
    ]
    )

env.StaticLibrary(
    target = libraryPath + libraryName, 
    source = filesCPP)
