import copy

Import('env_base')
Import('libraryPath')
Import('programPath')
Import('programName')
Import('binFolder')
Import('pathToBox2DLibrary')

pathToH = '#include'

SFMLLibraries = [
    '-lsfml-graphics', 
    '-lsfml-window', 
    '-lsfml-system'
]

programLibraries = [
    'events', 
    'screenLib', 
    'drawing'
]

externalLibraries = [
    'libbox2d.a'
]

objectFiles = [
    binFolder + 'graphic_library_facade/graphicLibraryFacade.o'
]

HFilesFolder = []

filesCPP = [
    'main.cpp',
    'renderLoop.cpp'
]



filesHMain = [pathToH + x for x in HFilesFolder]

env = env_base.Clone()

env.Append(
    CPPPATH = [
        'source/BD_FACADE', 
        'source/graphic_library_facade', 
        '#source/main',
        pathToH
        ],

        LIBS = SFMLLibraries + programLibraries + externalLibraries,

        LIBPATH = [
            libraryPath,
            pathToBox2DLibrary
        ]
)

programFile = env.Program(target = programPath + programName, source = filesHMain + filesCPP + objectFiles)

Return('programFile')
