#
#      Authors: Kordowski Mateusz, Przybysz Filip
#
Import('env_tests')
Import('libraryPath')
Import('testsFolder')
Import('pathToBox2DHeaders')
Import('sys')

pathToH = '#include/main/screen'

#testLibraries = [
#    'boost-system',
#    'boost-thread',
#    'boost_unit_test_framework'
#]

env = env_tests.Clone()

env.Append(
    CPPPATH = [
        '#libraries/boost_1_72_0',
	pathToH
    ],

    #LINKFLAGS = [
    #    '-Wl,-Bdynamic'
    #],

)

CPPFiles = [
    'ScreenTests.cc'
    ]

env.Program(target = "ScreenTests", source = CPPFiles)

