print('Building graphic library')

Import('env_base')

env = env_base.Clone(
    CPPPATH = ['../../libraries/boost_1_72_0'],
)

env.Object(target = 'graphicLibraryFacade', source = 'graphicLibraryFacade.cpp')
