#
#      Author: Kordowski Mateusz
#
Import('env_tests')
Import('binFolder')
Import('sys')

pathToH = '#include/main/event'

env = env_tests.Clone()

env.Append(
    CPPPATH = [
        '#libraries/boost_1_72_0',
        pathToH
    ]
)

if sys.platform.startswith('linux'):
    objectFiles = [
	'../../bin/BoostTestInclude.o'
    ]
else:
    objectFiles = [
	'../../bin/BoostTestInclude.obj'
    ]


CPPFiles = [
    'EventsTest.cc'
]


env.Program(target = "EventsTest", source = CPPFiles + objectFiles)
