#
#      Author: Kordowski Mateusz
#
Import('env_tests')
Import('binFolder')
Import('sys')

pathToH = '#include/main/program_events'

env = env_tests.Clone()

env.Append(
    CPPPATH = [
        '#libraries/boost_1_72_0',
        pathToH
    ]
)

#static libraries "undefined" error workaround
if sys.platform.startswith('linux'):
    objectFiles = [
        binFolder + 'main/program_events/BasicEvents.o',
        binFolder + 'main/program_events/EventManager.o',
        binFolder + 'main/program_events/EventSet.o',
        binFolder + 'main/program_events/UIEvents.o',
	'../../bin/BoostTestInclude.o'
    ]
else:
    objectFiles = [
        binFolder + 'main/program_events/BasicEvents.obj',
        binFolder + 'main/program_events/EventManager.obj',
        binFolder + 'main/program_events/EventSet.obj',
        binFolder + 'main/program_events/UIEvents.obj',
	'../../bin/BoostTestInclude.obj'
    ]


CPPFiles = [
    'EventsTest.cc'
]


env.Program(target = "EventsTest", source = CPPFiles + objectFiles)
