
Import('env_base')
Import('binFolder')
Import('pathToUtility')
Import('libraryPath')

pathToH = '#include/main/program_events/'
libraryName = 'events'

HFilesMain = [
    'eventInterface.h',
    'events.h',
]

HFilesUtility = [
    'setTemplate.h'
]

filesCPP = [
    'basicEvents.cpp',
    'eventSet.cpp',
    'eventManager.cpp',
    'UIEvents.cpp'
]



filesHMain = [pathToH + x for x in HFilesMain]
filesHUtil = [pathToUtility + x for x in HFilesUtility]

env = env_base.Clone(
    CPPPATH = pathToH
)


env.StaticLibrary(libraryPath + libraryName, filesHMain + filesHUtil + filesCPP)
