
Import('env_base')

env = env_base.Clone(
    CPPPATH = ['../../../source/main/program_events', '../../../source/main/utility']
)

env.StaticLibrary('../../../build/libs/events', ['basicEvents.cpp', 'eventSet.cpp', 'eventInterface.h', 'eventManager.cpp', 'UIEvents.cpp', '../../../source/main/utility/setTemplate.h', 'events.h'])
